/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#1b6489",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "secondary": "#45636d",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#2d4b55",
        "tertiary-container": "#a9000f",
        "tertiary": "#7d0008",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "tertiary-fixed": "#ffdad6",
        "on-surface-variant": "#40484e",
        "on-secondary-fixed": "#001f28",
        "tertiary-fixed-dim": "#ffb4ab",
        "on-tertiary-container": "#ffb3aa",
        "surface-container-low": "#f2f4f6",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "primary": "#00405b",
        "on-error-container": "#93000a",
        "inverse-primary": "#8fcef7",
        "outline": "#70787e",
        "on-secondary-container": "#4b6973",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed-variant": "#93000b",
        "on-primary-fixed-variant": "#004c6c",
        "on-primary-container": "#8fcdf6",
        "primary-container": "#00587c",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#410002",
        "primary-fixed-dim": "#8fcef7",
        "primary-fixed": "#c7e7ff",
        "surface-container-lowest": "#ffffff",
        "background": "#f7f9fb",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#accbd8",
        "on-background": "#191c1e",
        "secondary-fixed": "#c8e8f4",
        "on-error": "#ffffff",
        "surface": "#f7f9fb",
        "outline-variant": "#c0c7cf",
        "on-primary-fixed": "#001e2e",
        "secondary-container": "#c8e8f4",
        "inverse-on-surface": "#eff1f3",
        "surface-dim": "#d8dadc",
        "surface-container-high": "#e6e8ea"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        xs: "4px",
        xl: "40px",
        sm: "8px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        base: "4px",
        md: "16px",
        lg: "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "'Fira Code'", "Consolas", "monospace"],
        code: ["'JetBrains Mono'", "'Fira Code'", "Consolas", "monospace"],
      }
    }
  },
  plugins: [],
};
