version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    restart: unless-stopped

    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      TZ: "America/Guayaquil"
      PGTZ: "America/Guayaquil"

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  -d "]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - trazabilidad_net

    command: >
      postgres
        -c max_connections=100
        -c shared_buffers=256MB
        -c effective_cache_size=512MB
        -c work_mem=16MB
        -c maintenance_work_mem=64MB
        -c log_min_duration_statement=500
        -c log_timezone=America/Guayaquil

  adminer:
    image: adminer:latest
    container_name: adminer-container
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - trazabilidad_net

volumes:
  postgres_data:
    driver: local
    name: trazabilidad_postgres_data

networks:
  trazabilidad_net:
    driver: bridge
    name: trazabilidad_network